Menu improvements
kockatykalendar/frontend pull request #109
Opened 2021-04-01 15:45 UTC by krtko1

depends on #98, fixes #70 and #105

2021-04-01 16:34 UTC, ano95 requested changes
Prosím ťa, rozdel si tie PR tak, aby všade neboli commity z double-slidera 🙂

2021-04-01 18:26 UTC, krtko1 commented
> Prosím ťa, rozdel si tie PR tak, aby všade neboli commity z double-slidera

no ok...

2021-04-06 11:46 UTC, Zajozor commented
prosim ta odstran zmeny co su len formatting...
alebo sprav zvlast PR kde preformatujes naraz cele repo. Vsak to riesime uz asi v siedmom PR ze to nejak nahodne je :D

2021-04-08 13:03 UTC, Zajozor commented
Prosim odtranme formatting zmeny. alebo aspon do zvlast commitu, rad si to potom pozriem :)
Vyzorovo sa mi to zda ok.

2021-05-09 19:16 UTC, Zajozor commented
Kod sa mi zda v poriadku, funguje to podla mna spravne.

Ked uz ale tot prerabame, nepozrel by si sa prosim na to, preco je na stranke s exportom to menu uzsie? (vid gif)

![CleanShot 2021-05-09 at 21 16 03](https://user-images.githubusercontent.com/1835434/117584189-d0c10780-b10b-11eb-9cf7-6219278f93f2.gif)

2021-05-10 12:38 UTC, krtko1 commented
WTF fakt neviem prečo to robí. Ako na to pozerám, tak na to pozerám malo by to byť rovnaké.

2022-05-24 12:03 UTC, merged