Override search
kockatykalendar/frontend pull request #112
Opened 2021-04-01 22:43 UTC by krtko1

Na pc používa ctrl+f alebo F3 a seach bar funguje iba, keď je otvorený, svoj stav si však pamätá. Na mobile je search bar vo filter modale, funguje aj keď je modal zavretý, stav si neukladá asi by to iba zbytočne miatlo ľudí.

Celkovo hľadanie funguje na princípe `JSON.stringify(event).include(input)`. Na začiatok podľa mňa dostatočné, neskôr by sa dalo asi viac vyhrať.

depends on #98 (tailwind 2), implements a closes #107

2021-04-06 11:45 UTC, Zajozor commented
CMD+F na macu plz.

2021-04-06 11:45 UTC, Zajozor commented
zavisi tento PR nejak na features z inych? Ak nie, vies to plz tak spravit aby sa to dalo normalne reviewovat?

2021-05-09 19:06 UTC, Zajozor commented
Pekne to je, mozno dve poznamky:

- Tu animaciu dajme rychlejsiu, 1s je fakt moc. Mozno 200ms?

- Ked otvorim/zatvorim okienko, prescrolluje ma to na current event. To by som mozno zrusil 🤔 Potom co nieco napisem tak kludne, ale dovtedy asi nie.


p.s. skusal som aj ten mobilny search - a celkom pekne je to vyriesene, good job.

2021-05-10 13:10 UTC, krtko1 commented
> Ked otvorim/zatvorim okienko, prescrolluje ma to na current event. To by som mozno zrusil thinking Potom co nieco napisem tak kludne, ale dovtedy asi nie.

Hmm, problém je, že aktuálne pri každom zavolaní `render` funkcie updejtneš to čo sa zobrazuje a mimo iné nascroluješ na najaktuálnejší so zobrazovaných eventov.

- Možno sa dá oddeliť scroll a render funkciu? Neviem nakolko to dáva zmysel. 

- Prípadne vieme kontrolovať či si niečo spravil a ak nie, tak render vôbec nevolať. (najjednoduchšie riešenie)

- Eventuálne si vieme zapamätať nejaké stavy, medzi ktorými sa bude dať nejak pohybovať. Teda aj keď niečo napíšeš a zavrieš ten search, tak sa nedostaneš akoby na pôvodnú stránku ako keby si stlačil F5 ale do stavu v akom si bol pred stlačením F3. (Toto mi príde ako najlepšia alternatíva aj keď neviem či by som takú funkcionalitu nenechal na další pull request)

2021-05-12 19:38 UTC, ano95 requested changes
Prosím, ešte ten duration ako Zajo spomínal a môžeme mergovať.

2022-05-24 07:37 UTC, gardenerik approved these changes

2022-05-24 07:37 UTC, merged