add iuventa logo
kockatykalendar/frontend pull request #29
Opened 2020-10-30 19:26 UTC by krtko1

2020-10-30 19:58 UTC, ano95 requested changes
Nemali by sme UK logo, ktoré má menej ako 78kB? :smile:

2020-10-30 21:06 UTC, krtko1 commented
> Nemali by sme UK logo, ktoré má menej ako 78kB?

bolo vyrobené z png čo malo 113 kB... Mierne som ho optimalizoval (akože viac sa už asi fakt nedá bez straty kvality (Áno stále je asi dosť dobré aj na to aby išlo ako veľký obrázok do pozadia aj keď už to začína byť také funny)), teraz je to 27 kB (hej je to stále najviac zo všetkého čo máme ale aj originálny strom favicon mal 34 kb, tak asi fakt sa nedá ísť o moc nižšie)

2020-10-31 08:49 UTC, Zajozor commented
A nemozeme pouzit png velkosti 64x64 alebo nieco take, co bude mensie?

2020-10-31 10:07 UTC, ano95 commented
@krtko1 prebehol som iuventu aj matfyz optimalizatorom, toto je asi najlepsie, co vieme spravit.
treba sa rozhodnut, ci matfyz staci v PNG alebo chceme za kazdu cenu SVGcko, ktore je ~2x také veľké

2020-10-31 10:23 UTC, Zajozor commented
neni dovod force-ovat svg, pouzime png, kde sa hodi viac (hlavne kym ich zatial zobrazujeme len v malom)

2020-10-31 10:24 UTC, merged